{
  "openapi": "3.0.1",
  "info": {
    "title": "Conversations Inbox & Messages",
    "description": "Basepom for all HubSpot Projects",
    "version": "v3",
    "x-hubspot-product-tier-requirements": {
      "marketing": "FREE",
      "sales": "FREE",
      "service": "FREE",
      "cms": "FREE",
      "commerce": "FREE",
      "crmHub": "FREE",
      "dataHub": "FREE"
    },
    "x-hubspot-api-use-case": "If you're using the conversations inbox in HubSpot, but you want to report on support agent productivity in an external tool or export message data to an external service, you can build an integration with the conversations and messages API.",
    "x-hubspot-related-documentation": [
      {
        "name": "Inbox & Messages Guide",
        "url": "https://developers.hubspot.com/docs/guides/api/conversations/inbox-and-messages"
      }
    ],
    "x-hubspot-introduction": "Use the conversations API to manage and send messages via the connected channels in your conversations inbox. You can retrieve existing messages, update threads, and provide internal comments for agents on your team. ",
    "x-moar-merged": true,
    "x-moar-merged-count": 2
  },
  "servers": [
    {
      "url": "https://api.hubapi.com"
    }
  ],
  "tags": [
    {
      "name": "Public_Thread"
    },
    {
      "name": "Public_Inbox"
    },
    {
      "name": "Public_Channel_Account"
    },
    {
      "name": "Public_Channel"
    },
    {
      "name": "Public_Message"
    },
    {
      "name": "Public_Actor"
    },
    {
      "name": "External_Channel_Accounts"
    },
    {
      "name": "External_Messages"
    },
    {
      "name": "External_Channels"
    },
    {
      "name": "External_Channel_Account_Staging_Tokens"
    }
  ],
  "paths": {
    "/conversations/v3/conversations/inboxes": {
      "get": {
        "tags": [
          "Public_Inbox"
        ],
        "summary": "Get conversations inboxes",
        "description": "Retrieve a list of conversations inboxes, with optional filters and sorting.",
        "operationId": "get-/conversations/v3/conversations/inboxes",
        "security": [
          {
            "oauth2": [
              "conversations.read"
            ]
          },
          {
            "private_apps": [
              "conversations.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/conversations/v3/conversations/threads/{threadId}": {
      "get": {
        "tags": [
          "Public_Thread"
        ],
        "summary": "Get a single thread",
        "description": "Retrieve a single thread by its ID",
        "operationId": "get-/conversations/v3/conversations/threads/{threadId}",
        "security": [
          {
            "oauth2": [
              "conversations.read"
            ]
          },
          {
            "private_apps": [
              "conversations.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "delete": {
        "tags": [
          "Public_Thread"
        ],
        "summary": "Archives a thread",
        "description": "Archives a single thread. The thread will be permanently deleted 30 days after placed in an archived state.",
        "operationId": "delete-/conversations/v3/conversations/threads/{threadId}",
        "security": [
          {
            "private_apps": [
              "conversations.write"
            ]
          },
          {
            "oauth2": [
              "conversations.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "patch": {
        "tags": [
          "Public_Thread"
        ],
        "summary": "Update a thread",
        "description": "Updates a single thread. Either a thread's status can be updated, or the thread can be restored.",
        "operationId": "patch-/conversations/v3/conversations/threads/{threadId}",
        "security": [
          {
            "private_apps": [
              "conversations.write"
            ]
          },
          {
            "oauth2": [
              "conversations.write"
            ]
          }
        ],
        "x-moar-primitive-count": 2,
        "x-moar-complexity-skipped": false
      }
    },
    "/conversations/v3/conversations/threads/{threadId}/messages/{messageId}/original-content": {
      "get": {
        "tags": [
          "Public_Message"
        ],
        "summary": "Get the original content of a single message",
        "description": "Returns the complete original text and rich text bodies of a message. This will be different from the text and rich text in the message itself if the message's `truncationStatus` is anything other than `NOT_TRUNCATED`.",
        "operationId": "get-/conversations/v3/conversations/threads/{threadId}/messages/{messageId}/original-content",
        "security": [
          {
            "oauth2": [
              "conversations.read"
            ]
          },
          {
            "private_apps": [
              "conversations.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/conversations/v3/conversations/channels": {
      "get": {
        "tags": [
          "Public_Channel"
        ],
        "summary": "Get channels",
        "description": "Retrieve a list of channels, with optional filters and sorting.",
        "operationId": "get-/conversations/v3/conversations/channels",
        "security": [
          {
            "oauth2": [
              "conversations.read"
            ]
          },
          {
            "private_apps": [
              "conversations.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/conversations/v3/conversations/actors/{actorId}": {
      "get": {
        "tags": [
          "Public_Actor"
        ],
        "summary": "Get a single actor",
        "description": "Retrieve details of a single actor using the actor ID.",
        "operationId": "get-/conversations/v3/conversations/actors/{actorId}",
        "security": [
          {
            "oauth2": [
              "conversations.read"
            ]
          },
          {
            "private_apps": [
              "conversations.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/conversations/v3/conversations/threads": {
      "get": {
        "tags": [
          "Public_Thread"
        ],
        "summary": "Get threads",
        "description": "Retrieve a list of threads, with optional filters and sorting.",
        "operationId": "get-/conversations/v3/conversations/threads",
        "security": [
          {
            "oauth2": [
              "conversations.read"
            ]
          },
          {
            "private_apps": [
              "conversations.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/conversations/v3/conversations/threads/{threadId}/messages": {
      "get": {
        "tags": [
          "Public_Message"
        ],
        "summary": "Get message history for a thread",
        "description": "Retrieve the message history for a specific thread.",
        "operationId": "get-/conversations/v3/conversations/threads/{threadId}/messages",
        "security": [
          {
            "oauth2": [
              "conversations.read"
            ]
          },
          {
            "private_apps": [
              "conversations.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "post": {
        "tags": [
          "Public_Message"
        ],
        "summary": "Send a message to a thread",
        "description": "Send a new message on a thread at the current timestamp.",
        "operationId": "post-/conversations/v3/conversations/threads/{threadId}/messages",
        "security": [
          {
            "private_apps": [
              "conversations.write"
            ]
          },
          {
            "oauth2": [
              "conversations.write"
            ]
          }
        ],
        "x-moar-primitive-count": 47,
        "x-moar-complexity-skipped": false
      }
    },
    "/conversations/v3/conversations/actors/batch/read": {
      "post": {
        "tags": [
          "Public_Actor"
        ],
        "summary": "Get a group of actors",
        "description": "Resolve a set of `ActorId`s to the underlying actors/participants.",
        "operationId": "post-/conversations/v3/conversations/actors/batch/read",
        "security": [
          {
            "oauth2": [
              "conversations.read"
            ]
          },
          {
            "private_apps": [
              "conversations.read"
            ]
          }
        ],
        "x-moar-primitive-count": 1,
        "x-moar-complexity-skipped": false
      }
    },
    "/conversations/v3/conversations/channel-accounts/{channelAccountId}": {
      "get": {
        "tags": [
          "Public_Channel_Account"
        ],
        "summary": "Get a single channel account",
        "description": "Retrieve details of a single channel account using the channel account ID.",
        "operationId": "get-/conversations/v3/conversations/channel-accounts/{channelAccountId}",
        "security": [
          {
            "oauth2": [
              "conversations.read"
            ]
          },
          {
            "private_apps": [
              "conversations.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/conversations/v3/conversations/channel-accounts": {
      "get": {
        "tags": [
          "Public_Channel_Account"
        ],
        "summary": "Get channel accounts",
        "description": "Retrieve a list of channel accounts, with optional filters and sorting.",
        "operationId": "get-/conversations/v3/conversations/channel-accounts",
        "security": [
          {
            "oauth2": [
              "conversations.read"
            ]
          },
          {
            "private_apps": [
              "conversations.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/conversations/v3/conversations/channels/{channelId}": {
      "get": {
        "tags": [
          "Public_Channel"
        ],
        "summary": "Get a single channel",
        "description": "Retrieve details of a single channel using the channel ID.",
        "operationId": "get-/conversations/v3/conversations/channels/{channelId}",
        "security": [
          {
            "oauth2": [
              "conversations.read"
            ]
          },
          {
            "private_apps": [
              "conversations.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/conversations/v3/conversations/inboxes/{inboxId}": {
      "get": {
        "tags": [
          "Public_Inbox"
        ],
        "summary": "Get a single conversations inbox",
        "description": "Retrieve details of a single conversations inbox using the inbox ID.",
        "operationId": "get-/conversations/v3/conversations/inboxes/{inboxId}",
        "security": [
          {
            "oauth2": [
              "conversations.read"
            ]
          },
          {
            "private_apps": [
              "conversations.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/conversations/v3/conversations/threads/{threadId}/messages/{messageId}": {
      "get": {
        "tags": [
          "Public_Message"
        ],
        "summary": "Get a single message",
        "description": "Retrieve a single message from a thread using the message ID.",
        "operationId": "get-/conversations/v3/conversations/threads/{threadId}/messages/{messageId}",
        "security": [
          {
            "oauth2": [
              "conversations.read"
            ]
          },
          {
            "private_apps": [
              "conversations.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/conversations/v3/custom-channels/{channelId}": {
      "get": {
        "tags": [
          "External_Channels"
        ],
        "summary": "Get a custom channel",
        "description": "Retrieve the details about a custom channel. This API allows you to see a custom channel's current capabilties and other configuration metadata",
        "operationId": "get-/conversations/v3/custom-channels/{channelId}",
        "security": [
          {
            "developer_hapikey": []
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "delete": {
        "tags": [
          "External_Channels"
        ],
        "summary": "Archive a custom channel",
        "description": "Archive an existing registered custom channel",
        "operationId": "delete-/conversations/v3/custom-channels/{channelId}",
        "security": [
          {
            "developer_hapikey": []
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "patch": {
        "tags": [
          "External_Channels"
        ],
        "summary": "Update a custom channel",
        "description": "Update the capabilities for an existing. You can also use it to update the channel's webhookUri and its channelAccountConnectionRedirectUrl.",
        "operationId": "patch-/conversations/v3/custom-channels/{channelId}",
        "security": [
          {
            "developer_hapikey": []
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/conversations/v3/custom-channels/{channelId}/messages/{messageId}": {
      "get": {
        "tags": [
          "External_Messages"
        ],
        "summary": "Get a message",
        "description": "Get the details for a specific message sent over a custom channel",
        "operationId": "get-/conversations/v3/custom-channels/{channelId}/messages/{messageId}",
        "security": [
          {
            "oauth2": [
              "conversations.custom_channels.read"
            ]
          },
          {
            "private_apps": [
              "conversations.custom_channels.read"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "patch": {
        "tags": [
          "External_Messages"
        ],
        "summary": "Update a message ",
        "description": "Update a message's status to indicate if it was successfully sent, failed to send, or was read. For failed messages, this can also include the error message for the failure.",
        "operationId": "patch-/conversations/v3/custom-channels/{channelId}/messages/{messageId}",
        "security": [
          {
            "private_apps": [
              "conversations.custom_channels.write"
            ]
          },
          {
            "oauth2": [
              "conversations.custom_channels.write"
            ]
          }
        ],
        "x-moar-primitive-count": 2,
        "x-moar-complexity-skipped": false
      }
    },
    "/conversations/v3/custom-channels/{channelId}/channel-account-staging-tokens/{accountToken}": {
      "patch": {
        "tags": [
          "External_Channel_Account_Staging_Tokens"
        ],
        "summary": "Update a channel account staging token",
        "description": "Update a channel account staging token's account name and delivery identifier. This information will be applied to the channel account created from this staging token. This is used for public apps.",
        "operationId": "patch-/conversations/v3/custom-channels/{channelId}/channel-account-staging-tokens/{accountToken}",
        "security": [
          {
            "oauth2": [
              "conversations.custom_channels.read"
            ]
          },
          {
            "private_apps": [
              "conversations.custom_channels.read"
            ]
          },
          {
            "private_apps": [
              "conversations.custom_channels.write"
            ]
          },
          {
            "oauth2": [
              "conversations.custom_channels.write"
            ]
          }
        ],
        "x-moar-primitive-count": 3,
        "x-moar-complexity-skipped": false
      }
    },
    "/conversations/v3/custom-channels/{channelId}/channel-accounts": {
      "get": {
        "tags": [
          "External_Channel_Accounts"
        ],
        "summary": "Get accounts for a channel",
        "description": "Retrieve a list of accounts for a custom channel.",
        "operationId": "get-/conversations/v3/custom-channels/{channelId}/channel-accounts",
        "security": [
          {
            "oauth2": [
              "conversations.custom_channels.read"
            ]
          },
          {
            "private_apps": [
              "conversations.custom_channels.read"
            ]
          },
          {
            "private_apps": [
              "conversations.custom_channels.write"
            ]
          },
          {
            "oauth2": [
              "conversations.custom_channels.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "post": {
        "tags": [
          "External_Channel_Accounts"
        ],
        "summary": "Create a channel account",
        "description": "Create a new account for a channel. Multiple accounts can communicate over a single channel using different delivery identifiers.",
        "operationId": "post-/conversations/v3/custom-channels/{channelId}/channel-accounts",
        "security": [
          {
            "oauth2": [
              "conversations.custom_channels.read"
            ]
          },
          {
            "private_apps": [
              "conversations.custom_channels.read"
            ]
          },
          {
            "private_apps": [
              "conversations.custom_channels.write"
            ]
          },
          {
            "oauth2": [
              "conversations.custom_channels.write"
            ]
          }
        ],
        "x-moar-primitive-count": 5,
        "x-moar-complexity-skipped": false
      }
    },
    "/conversations/v3/custom-channels/{channelId}/channel-accounts/{channelAccountId}": {
      "get": {
        "tags": [
          "External_Channel_Accounts"
        ],
        "summary": "Get a channel account by id",
        "description": "Retrieve the details for a specific channel account. This contains all the metadata about your channel account, including its channel, associated inbox id, and delivery identifier information.",
        "operationId": "get-/conversations/v3/custom-channels/{channelId}/channel-accounts/{channelAccountId}",
        "security": [
          {
            "oauth2": [
              "conversations.custom_channels.read"
            ]
          },
          {
            "private_apps": [
              "conversations.custom_channels.read"
            ]
          },
          {
            "private_apps": [
              "conversations.custom_channels.write"
            ]
          },
          {
            "oauth2": [
              "conversations.custom_channels.write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "patch": {
        "tags": [
          "External_Channel_Accounts"
        ],
        "summary": "Update a channel account",
        "description": "This API is used to update the name of the channel account and it's isAuthorized status. Setting to isAuthorized flag to False disables the channel account.",
        "operationId": "patch-/conversations/v3/custom-channels/{channelId}/channel-accounts/{channelAccountId}",
        "security": [
          {
            "oauth2": [
              "conversations.custom_channels.read"
            ]
          },
          {
            "private_apps": [
              "conversations.custom_channels.read"
            ]
          },
          {
            "private_apps": [
              "conversations.custom_channels.write"
            ]
          },
          {
            "oauth2": [
              "conversations.custom_channels.write"
            ]
          }
        ],
        "x-moar-primitive-count": 2,
        "x-moar-complexity-skipped": false
      }
    },
    "/conversations/v3/custom-channels/": {
      "get": {
        "tags": [
          "External_Channels"
        ],
        "summary": "Get all channels for app",
        "description": "Retrieve all custom channels associated with the app.",
        "operationId": "get-/conversations/v3/custom-channels/",
        "security": [
          {
            "developer_hapikey": []
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "post": {
        "tags": [
          "External_Channels"
        ],
        "summary": "Create a custom channel",
        "description": "Register a new channel along with its capabilities and the webhook url that will be used to receive messages published over the channel",
        "operationId": "post-/conversations/v3/custom-channels/",
        "security": [
          {
            "developer_hapikey": []
          }
        ],
        "x-moar-primitive-count": 5,
        "x-moar-complexity-skipped": false
      }
    },
    "/conversations/v3/custom-channels/{channelId}/messages": {
      "post": {
        "tags": [
          "External_Messages"
        ],
        "summary": "Publish a message",
        "description": "Publish a message over your custom channel",
        "operationId": "post-/conversations/v3/custom-channels/{channelId}/messages",
        "security": [
          {
            "private_apps": [
              "conversations.custom_channels.write"
            ]
          },
          {
            "oauth2": [
              "conversations.custom_channels.write"
            ]
          }
        ],
        "x-moar-primitive-count": 19,
        "x-moar-complexity-skipped": false
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
            "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
            "scopes": {
              "conversations.read": "Read from conversations",
              "conversations.write": "Write to conversations",
              "conversations.custom_channels.read": "Read messages and manage Channel Accounts for an included Custom Channel.",
              "conversations.custom_channels.write": "Publish messages into HubSpot and manage Channel Accounts for an included Custom Channel."
            }
          }
        }
      },
      "private_apps": {
        "type": "apiKey",
        "name": "private-app",
        "in": "header"
      },
      "developer_hapikey": {
        "type": "apiKey",
        "name": "hapikey",
        "in": "query"
      }
    }
  },
  "x-hubspot-product-tier-requirements": {
    "marketing": "FREE",
    "sales": "FREE",
    "service": "FREE",
    "cms": "FREE",
    "commerce": "FREE",
    "crmHub": "FREE",
    "dataHub": "FREE"
  }
}