{
  "openapi": "3.0.1",
  "info": {
    "title": "Events Events",
    "version": "v3",
    "x-hubspot-product-tier-requirements": {
      "marketing": "ENTERPRISE",
      "sales": "ENTERPRISE",
      "service": "ENTERPRISE",
      "cms": "ENTERPRISE",
      "commerce": "FREE",
      "crmHub": "FREE",
      "dataHub": "FREE"
    },
    "x-hubspot-api-use-case": "You want to view a timeline of the interactions that a contact has had with your content. You can then use this timeline to build a dataset for custom analytics or present a contact timeline in an external application.",
    "x-hubspot-related-documentation": [
      {
        "name": "Web Analytics Guide",
        "url": "https://developers.hubspot.com/docs/guides/api/analytics-and-events/event-analytics"
      }
    ],
    "x-hubspot-introduction": "Use the web analytics API to fetch events associated with CRM records of any type. This includes standard events, such as website page views and email opens, as well as custom events.",
    "x-moar-merged": true,
    "x-moar-merged-count": 3
  },
  "servers": [
    {
      "url": "https://api.hubapi.com"
    }
  ],
  "tags": [
    {
      "name": "Events"
    },
    {
      "name": "Event definition"
    },
    {
      "name": "Batch"
    },
    {
      "name": "Basic"
    }
  ],
  "paths": {
    "/events/v3/events/": {
      "get": {
        "tags": [
          "Events"
        ],
        "summary": "Retrieve event data",
        "description": "Retrieve instances of event completion data. For example, retrieve all event completions associated with a specific contact.",
        "operationId": "get-/events/v3/events/_getPage",
        "security": [
          {
            "oauth2": [
              "oauth"
            ]
          },
          {
            "private_apps": [
              "oauth"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/events/v3/events/event-types": {
      "get": {
        "tags": [
          "Events"
        ],
        "summary": "Event Types",
        "description": "This endpoint returns a list of event type names which are visible to you. You may use these event type names to query the API for specific event instances of a desired type.\n\nNote: the `get_types` method is only supported in the Python SDK version `12.0.0-beta.1` or later. ",
        "operationId": "get-/events/v3/events/event-types_getTypes",
        "security": [
          {
            "oauth2": [
              "oauth"
            ]
          },
          {
            "private_apps": [
              "oauth"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      }
    },
    "/events/v3/event-definitions": {
      "get": {
        "tags": [
          "Event definition"
        ],
        "summary": "Retrieve event definitions",
        "description": "Retrieve existing custom event definitions.",
        "operationId": "get-/events/v3/event-definitions",
        "security": [
          {
            "private_apps": [
              "behavioral_events.event_definitions.read_write"
            ]
          },
          {
            "oauth2": [
              "behavioral_events.event_definitions.read_write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "post": {
        "tags": [
          "Event definition"
        ],
        "summary": "Create custom event definition",
        "description": "Create a custom event definition.",
        "operationId": "post-/events/v3/event-definitions",
        "security": [
          {
            "private_apps": [
              "behavioral_events.event_definitions.read_write"
            ]
          },
          {
            "oauth2": [
              "behavioral_events.event_definitions.read_write"
            ]
          }
        ],
        "x-moar-primitive-count": 13,
        "x-moar-complexity-skipped": false
      }
    },
    "/events/v3/event-definitions/{eventName}": {
      "get": {
        "tags": [
          "Event definition"
        ],
        "summary": "Retrieve a custom event definition",
        "description": "Fetch a single custom event definition by name.",
        "operationId": "get-/events/v3/event-definitions/{eventName}",
        "security": [
          {
            "private_apps": [
              "behavioral_events.event_definitions.read_write"
            ]
          },
          {
            "oauth2": [
              "behavioral_events.event_definitions.read_write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "delete": {
        "tags": [
          "Event definition"
        ],
        "summary": "Delete an event definition",
        "description": "Delete a custom event definition by name.",
        "operationId": "delete-/events/v3/event-definitions/{eventName}",
        "security": [
          {
            "private_apps": [
              "behavioral_events.event_definitions.read_write"
            ]
          },
          {
            "oauth2": [
              "behavioral_events.event_definitions.read_write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "patch": {
        "tags": [
          "Event definition"
        ],
        "summary": "Update a custom event definition",
        "description": "Update a specific custom event definition by name.",
        "operationId": "patch-/events/v3/event-definitions/{eventName}",
        "security": [
          {
            "private_apps": [
              "behavioral_events.event_definitions.read_write"
            ]
          },
          {
            "oauth2": [
              "behavioral_events.event_definitions.read_write"
            ]
          }
        ],
        "x-moar-primitive-count": 2,
        "x-moar-complexity-skipped": false
      }
    },
    "/events/v3/event-definitions/{eventName}/property": {
      "post": {
        "tags": [
          "Event definition"
        ],
        "summary": "Create a property for an event definition",
        "description": "Create a new property for an existing event definition.",
        "operationId": "post-/events/v3/event-definitions/{eventName}/property",
        "security": [
          {
            "private_apps": [
              "behavioral_events.event_definitions.read_write"
            ]
          },
          {
            "oauth2": [
              "behavioral_events.event_definitions.read_write"
            ]
          }
        ],
        "x-moar-primitive-count": 9,
        "x-moar-complexity-skipped": false
      }
    },
    "/events/v3/event-definitions/{eventName}/property/{propertyName}": {
      "delete": {
        "tags": [
          "Event definition"
        ],
        "summary": "Delete a property from a custom event definition",
        "description": "Delete an existing property from a custom event definition.",
        "operationId": "delete-/events/v3/event-definitions/{eventName}/property/{propertyName}",
        "security": [
          {
            "private_apps": [
              "behavioral_events.event_definitions.read_write"
            ]
          },
          {
            "oauth2": [
              "behavioral_events.event_definitions.read_write"
            ]
          }
        ],
        "x-moar-primitive-count": 0,
        "x-moar-complexity-skipped": false
      },
      "patch": {
        "tags": [
          "Event definition"
        ],
        "summary": "Update an existing custom event property",
        "description": "Update an existing property in a custom event definition.",
        "operationId": "patch-/events/v3/event-definitions/{eventName}/property/{propertyName}",
        "security": [
          {
            "private_apps": [
              "behavioral_events.event_definitions.read_write"
            ]
          },
          {
            "oauth2": [
              "behavioral_events.event_definitions.read_write"
            ]
          }
        ],
        "x-moar-primitive-count": 7,
        "x-moar-complexity-skipped": false
      }
    },
    "/events/v3/send/batch": {
      "post": {
        "tags": [
          "Batch"
        ],
        "summary": "Send a batch of event completions",
        "description": "Send multiple event completions at once.",
        "operationId": "post-/events/v3/send/batch_send",
        "security": [
          {
            "oauth2": [
              "analytics.behavioral_events.send"
            ]
          },
          {
            "private_apps": [
              "analytics.behavioral_events.send"
            ]
          }
        ],
        "x-moar-primitive-count": 6,
        "x-moar-complexity-skipped": false
      }
    },
    "/events/v3/send": {
      "post": {
        "tags": [
          "Basic"
        ],
        "summary": "Send a custom event completion",
        "description": "Send data for a single event completion.",
        "operationId": "post-/events/v3/send_send",
        "security": [
          {
            "oauth2": [
              "analytics.behavioral_events.send"
            ]
          },
          {
            "private_apps": [
              "analytics.behavioral_events.send"
            ]
          }
        ],
        "x-moar-primitive-count": 6,
        "x-moar-complexity-skipped": false
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
            "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
            "scopes": {
              "oauth": "User and Account Information",
              "behavioral_events.event_definitions.read_write": "Read from and write to custom behavioral events definitions",
              "analytics.behavioral_events.send": "Send Behavioral Event Completions"
            }
          }
        }
      },
      "private_apps": {
        "type": "apiKey",
        "name": "private-app",
        "in": "header"
      }
    }
  },
  "x-hubspot-available-client-libraries": [
    "Node",
    "Python",
    "Ruby",
    "PHP"
  ],
  "x-hubspot-product-tier-requirements": {
    "marketing": "ENTERPRISE",
    "sales": "ENTERPRISE",
    "service": "ENTERPRISE",
    "cms": "ENTERPRISE",
    "commerce": "FREE",
    "crmHub": "FREE",
    "dataHub": "FREE"
  }
}